### ISSUE TITLE
set animations to data attributes

### ISSUE THREAD

**Issue by area73** [haiticss/haiticss#53]
Hi @danifornells ,
Thanks for you talk the other day in Madrid.
As we discuss ,I think there will be a good practice to have all the animations set in a data attribute instead on a class (same with JS interaction ) . Something like this:
[data-animation="a-reveal-opacity"] {}

you also said that you could have other animation elements in other layers and I see that your animation layer is almost at the bottom of the stack.
This makes me think in two issues.
The first one is that we can't asure the override of the animation rule because we don't have !important
The other one is more about "single source of truth principle". 
If a developer has to fix something on a module  that has a mixin like:
<div class="c-my-component a-reveal-opacity">
The developer will have to look into both files and do some testing to see which one is the one that is affecting the behavior (we are not fulfilling the single source of truth) .
this is one of the reasons that I don't like very much the use of mixin , except if the mixings are utilities (in this case we can asure that the utility is overriding the other elements on the mixin).

So mi proposal will be to refactor animation to be set with data attributes and maybe (and here I have my doubts) do not let have animation stuff inside our components, object, etc or in the wirst case tread animations as utilities with !important.

What do you think ?

**Comment by danifornells** [comment]
Hi @area73 , thanks for contributing, you're welcome ;)

The animations layer is not at bottom, because is a design abstraction that can be inherited by components, as you can see on the [haiticss triangle](https://haiticss.io/img/haiticss-triangle.svg). No matter what order has the three abstraction layers (objects, animations and color-shemes), but those three should be after elements and before components.

If I understood your concerns, those are:
1. - Serving abstractions as a mixins, and applying them on components, can break the single source of truth, while you can achieve same results adding the abstraction class on HTML. You need to check both component and animation css files to have the whole picture of properties.
2. - The animation inherited properties, could be overridden by other animation properties if any are set on component layer.

I can understand and share parts of the same concerns, but I have doubts about your proposal as a solution for them.

1. - About serving abstractions as a mixins and class names as well. There's a reason why we did it. If we consider the objects layer, and real world cases, we found components who mutates the object abstraction under certain conditions, like a matched breakpoint. On those cases we thought on many solutions, and concluded the best to define that complex or mutable layout in the component level. Mixins can help on that. But the usage of those mixins as a replacement for the inheritance of abstractions, let's say that's not a best practice, because you'll get more css output, and you loose the stronger point of the architecture. After playing with ITCSS the best practice that achieved better results on our cases, is to use the abstractions as class names on HTML, and write on component css file, just the properties that cannot be inherited, reserving to use utilities class names, to keep room for exceptions. It worked like a charm for us, and we believe that's the best way to go.

2. - About overriding abstractions properties on component levels. Sometimes is needed, for instance different vertical and horizontal paddings on objects. If happens, is better to override them on component css rather than using utilities class names.


Besides the concerns, your proposal was to use data-attributes, or let's say just attributes, to set animations. For me does not make a lot of sense, because all other abstractions are working based on class names, and you'll get a difference on a layer, but having same specificity on selectors. Besides that, I like the idea of attributes for determining the states of an animation or a component (not modifiers).

Maybe involving more people on that conversation we'll find the light.
Knock, knock @d-asensio @judabelli @arnau-pujol @nucliweb

**Comment by arnau-pujol** [comment]
Hi!

I get the @area73 points, but my opinion is similar to @danifornells, I prefer to use the classes and mantain the mixins, but I have to say that I like the idea of use data-attributes to set the animations states as well!

**Comment by area73** [comment]
OK, then I think we can close this issue
